route:
  host: itop.lt-mut-nonprod-scw.les-tilleuls.solutions

mariadb:
  auth:
    existingSecret: itop-mariadb-auth
  backup:
    enabled: true
    maxRetention: "72h" # 3 jours
    storage:
      s3:
        bucket: lt-mut-nonprod-scw-itop-mariadb-backup
