<?php
/**
 * Module itop-time-tracking
 *
 * @copyright   Copyright (C) 2012-2019 Combodo SARL
 * @license     https://www.combodo.com/documentation/combodo-software-license.html
 */

Dict::Add('FR FR', 'French', 'Français', array(
	'TimeTracking:TitlePage' => 'Suivi du temps',
	'TimeTracking:TrackingTimeOn' => 'Suivi du temps sur',
	'TimeTracking:PressButtonToStartTrackingOn' => 'Appuyez sur démarrer pour enregistrer du temps sur',
	'TimeTracking:TrackingTimeOnDiffObj' => 'Suivi du temps sur un autre objet',
	'TimeTracking:TrackingTimeStopwatchForcedStop' => 'Chronomètre arrêté de force',
	'TimeTracking:Category:Favorite' => 'Favoris',
	'TimeTracking:Category:All' => 'Tous',
	'TimeTracking:TabLabel' => 'Saisir mon temps',
	'TimeTracking:ReportTabLabel' => 'Rapport de temps',
	'TrackingTime:AddTimeSpent' => 'Ajouter du temps passé',
	'TimeTracking:ClassicMode' => 'Mode classique',
	'TimeTracking:ModalMode' => 'Mode modal',
	'TimeTracking::TrackedFrom:calendar' => 'Enregistré depuis le calendrier',
	'TimeTracking::TrackedFrom:stopwatch' => 'Enregistré depuis le chronomètre',
	'TimeTracking::TrackedFrom:manual' => 'Enregistré manuellement',

	'TimeTracking:SelectColorForActivity' => 'Choisir les couleurs de l\'activité',
	'TimeTracking:SetColor' => 'Appliquer les couleurs',	
	'TimeTacking:Stopwatch:Start' => 'Démarrer',
	'TimeTacking:Stopwatch:Stop' => 'Arrêter',
	'TimeTacking:Stopwatch:Reset' => 'Réinitialiser',
	'TimeTracking:SelectActivity:Placeholder' => 'Sélectionnez une activité',
	'TimeSpent:Edition' => 'Édition',
	'TimeSpent:Information' => 'Informations additionnelles',
	
	'TimeTracking:DayOfWeek-0' => 'Dim',
	'TimeTracking:DayOfWeek-1' => 'Lun',
	'TimeTracking:DayOfWeek-2' => 'Mar',
	'TimeTracking:DayOfWeek-3' => 'Mer',
	'TimeTracking:DayOfWeek-4' => 'Jeu',
	'TimeTracking:DayOfWeek-5' => 'Ven',
	'TimeTracking:DayOfWeek-6' => 'Sam',

	'TimeTracking:ReportActivityPerUser' => 'Durée d\'Activité cumulée par Utilisateur (en heures)',
	'TimeTracking:ReportActivityPerCustomer' => 'Durée d\'Activité cumulée par Client (en heures)',
	
	'TimeTracking:Title:MyActivities' => 'Mon rapport de suivi du temps',
	'TimeTracking:Title:Report' => 'Rapport de suivi du temps',
	'TimeTracking:Button:Close' => 'Fermer',
	'TimeTracking:Today' => 'Aujourd\'hui',
	'TimeTracking:Month' => 'Mois',
	'TimeTracking:Week' => 'Semaine',
	'TimeTracking:Day' => 'Jour',
	'TimeTracking:Total_Duration' => 'Durée totale: %1$s',
	'TimeTracking:Daily' => 'Rapport Journalier',
	'TimeTracking:Weekly' => 'Rapport Hedbomadaire',
	'TimeTracking:Monthly' => 'Rapport Mensuel',
	'TimeTracking:DailyNext' => ' Jour suiv. ► ',
	'TimeTracking:DailyPrev' => ' ◄ Jour préc. ',
	'TimeTracking:WeeklyNext' => ' Semaine suiv. ► ',
	'TimeTracking:WeeklyPrev' => ' ◄ Semaine préc. ',
	'TimeTracking:MonthlyNext' => ' Mois suiv. ► ',
	'TimeTracking:MonthlyPrev' => ' ◄ Mois préc. ',
	'TimeTracking:Report_From_To' => 'Du %1$s au %2$s',
	'TimeTracking:DateRangeFormat' => 'd/m',
	'TimeTracking:DayFormat' => 'd/m/Y',
	'TimeTracking:MoreCriteria' => 'Plus de critères',
	'TimeTracking:LessCriteria' => 'Moins de critères',
	'TimeTracking:ReportOverview:Label' => 'Vue d\'ensemble du temps passé',
	'TimeTracking:ReportOverview:ContactHeader' => 'Contact',
	'TimeTracking:ReportOverview:DurationHeader' => 'Temps total',
	'TimeTracking:ReportOverview:RequiredDurationHeader' => 'Temps requis',
	'TimeTracking:TimeSpentReport:Label' => 'Rapport du temps passé',

	'TimeTracking:Error:Generic' => 'Quelquechose s\'est mal passé',
	'TimeTracking:Error:WrongActivity' => 'Impossible d\'effection l\'action sur cette activité',
	'TimeTracking:Error:DeleteExpired' => 'Cet évènement est trop vieux, vous ne pouvez pas le supprimer',
	'TimeTracking:Error:DeleteArchived' => 'Cet évènement est archivé, vous ne pouvez pas le supprimer',
	'TimeTracking:Error:DeleteRights' => 'Droits insuffisants pour supprimer cet évènement',
	'TimeTracking:Error:UpdateExpired' => 'Cet évènement est trop vieux, vous ne pouvez pas le modifier',
	'TimeTracking:Error:UpdateRights' => 'Droits insuffisants pour modifier cet évènement',

	'Menu:TimeTracking' => 'Suivi du temps',
	'Menu:TimeTrackingPage' => 'Enregistrer mon temps',
	'Menu:MyTimeTrackingReport' => 'Mon rapport de suivi du temps',
	'Menu:TimeTrackingReport' => 'Rapport de suivi du temps',

	'Class:Activity' => 'Activité',
	'Class:Activity/Attribute:background_color' => 'Couleur de fond',
	'Class:Activity/Attribute:text_color' => 'Couleur du texte',
	'Class:Activity/Attribute:obj_class' => 'Class de l\'objet',
	'Class:Activity/Attribute:obj_id' => 'Id de l\'objet',
	'Class:Activity/Attribute:label' => 'Label',


	'Class:TimeSpent' => 'Temps passé',
	'Class:TimeSpent/Attribute:activity_id' => 'Activité',
	'Class:TimeSpent/Attribute:activity_label' => 'Label de l\'activité',
	'Class:TimeSpent/Attribute:contact_id' => 'Contact',
	'Class:TimeSpent/Attribute:contact_id_finalclass_recall' => 'Classe du contact',
	'Class:TimeSpent/Attribute:duration' => 'Durée',
	'Class:TimeSpent/Attribute:description' => 'Description',
	'Class:TimeSpent/Attribute:end_date' => 'Date de fin', 
	'Class:TimeSpent/Attribute:org_id' => 'Organisation',
	'Class:TimeSpent/Attribute:origin' => 'Origine',
	'Class:TimeSpent/Attribute:start_date' => 'Date de début',
	'Class:TimeSpent/Attribute:title' => 'Titre',
	'Class:TimeSpent/Attribute:user_id' => 'Utilisateur',
	'Class:TimeSpent/Attribute:user_id_finalclass_recall' => 'Classe de utilisateur',
	'Class:TimeSpent/Attribute:origin/Value:calendar' => 'calendrier',
	'Class:TimeSpent/Attribute:origin/Value:stopwatch' => 'chronomètre',
	'Class:TimeSpent/Attribute:origin/Value:manual' => 'manuel',

	'Class:TimeSpentBackground' => 'Temps passé d\'arrière plan',
	'Class:TimeSpentBackground/Attribute:status' => 'Status',

	'Class:FavouriteActivity' => 'Activité favorite',
	'Class:FavouriteActivity/Attribute:activity_id' => 'Activité',
	'Class:FavouriteActivity/Attribute:user_id' => 'Utilisateur',
	'Class:FavouriteActivity/Attribute:user_id_finalclass_recall' => 'Classe de utilisateur',

	'Class:UserColorActivity' => 'Couleur de l\'activité par utilisateur',
	'Class:UserColorActivity/Attribute:background_color' => 'Couleur de fond',
	'Class:UserColorActivity/Attribute:text_color' => 'Couleur du texte',
	'Class:UserColorActivity/Attribute:activity_id' => 'Activité',
	'Class:UserColorActivity/Attribute:user_id' => 'Utilisateur',

	'Class:TriggerOnForceStopTimeSpentBackground' => 'Déclencheur sur l\'arrêt forcé d\'un chronomètre de time tracking',
	'Class:TriggerOnForceStopTimeSpentBackground+' => 'Déclencheur sur l\'arrêt forcé d\'un chronomètre de time tracking par le cron',
));

