<?php
//
// File generated by ... on the 2023-03-20T17:05:29+0100
// Please do not edit manually
//

/**
 * Classes and menus for itop-time-tracking (version 2.3.3)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

/**
 * Snippet: TimeTrackingRightsPlugin
 */

class TimeTrackingRightsPlugin implements iApplicationObjectExtension
{

	public function OnIsModified($oObject)
	{
		return false;
	}

	public function OnCheckToWrite($oObject)
	{
		$iMaxEventAge = utils::GetConfig()->GetModuleSetting(TimeTrackingView::MODULE_CODE, 'delete_max_event_age', 30);

		$aError = array();
		if($oObject instanceof TimeSpent)
		{
		    $oUser = UserRights::GetUserObject();
		
            //Check if the timespent is not too old
			$sNow = time();
			$sEndDate = strtotime($oObject->Get('end_date'));
			if(empty($oObject->Get('end_date')))
			{
			    $sEndDate = strtotime($oObject->Get('start_date'));
			}
			
			$iDateDiff = round(($sNow - $sEndDate) / (60 * 60 * 24));
			if ($iMaxEventAge != 0 && $iDateDiff > $iMaxEventAge && 
			!(UserRights::HasProfile('Time Tracking Manager', $oUser) || UserRights::IsAdministrator($oUser)))
			{
				$aError[] = Dict::S('TimeTracking:Error:UpdateExpired');
			}
			
			//Check user rights on the timespent
            if(!$oObject->Get('user_id') == UserRights::GetUserId() && 
            !(UserRights::HasProfile('Time Tracking Manager', $oUser) || UserRights::IsAdministrator($oUser)))
            {
                $aError[] = Dict::S('TimeTracking:Error:UpdateRights');
            }
			
		}
		return $aError;
	}

	public function OnCheckToDelete($oObject)
	{
		$iMaxEventAge = utils::GetConfig()->GetModuleSetting(TimeTrackingView::MODULE_CODE, 'delete_max_event_age', 30);

		$aError = array();
		if($oObject instanceof TimeSpent)
		{
            $oUser = UserRights::GetUserObject();

            //Check if the timespent is not too old
			$sNow = time();
			$sEndDate = strtotime($oObject->Get('end_date'));
			if(empty($oObject->Get('end_date')))
			{
			    $sEndDate = strtotime($oObject->Get('start_date'));
			}
			
			$iDateDiff = round(($sNow - $sEndDate) / (60 * 60 * 24));
			if ($iMaxEventAge != 0 && $iDateDiff > $iMaxEventAge && 
			!(UserRights::HasProfile('Time Tracking Manager', $oUser) || UserRights::IsAdministrator($oUser)))
			{
				$aError[] = Dict::S('TimeTracking:Error:DeleteExpired');
			}
			
			//Check user rights on the timespent
            if(!($oObject->Get('user_id') == UserRights::GetUserId()) && 
            !(UserRights::HasProfile('Time Tracking Manager', $oUser) || UserRights::IsAdministrator($oUser)))
            {
                $aError[] = Dict::S('TimeTracking:Error:DeleteRights');
            }
			
		}
		return $aError;
	}

	public function OnDBUpdate($oObject, $oChange = null)
	{
	}

	public function OnDBInsert($oObject, $oChange = null)
	{
	}

	public function OnDBDelete($oObject, $oChange = null)
	{
	}
	
	public static function HasStopwatchDisplayRights($oUser)
	{
	  return UserRights::HasProfile('Time Tracker', $oUser) ||  UserRights::IsAdministrator($oUser);
	}	
	
	public static function HasTimeTrackingTabDisplayRights($oUser)
	{
		  return UserRights::HasProfile('Time Tracker', $oUser) ||  UserRights::IsAdministrator($oUser);
	}	
	
    public static function HasTimeTrackingReportTabDisplayRights($oUser)
	{
		  return UserRights::HasProfile('Time Tracker', $oUser) ||  UserRights::IsAdministrator($oUser);
	}
	
    public static function HasAllReportDisplayRights($oUser)
	{
	  return UserRights::HasProfile('Time Tracking Manager', $oUser) || UserRights::IsAdministrator($oUser);
	}
}
        



class Activity extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array(			'category' => 'addon,searchable,application,bizmodel',
			'key_type' => 'autoincrement',
			'name_attcode' => array('obj_class', 'obj_id'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(''),
			'db_table' => 'activity',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',
			'style' =>  new ormStyle(null, null, null, null, null, null),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("label", array("allowed_values"=>null, "sql"=>'label', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeString("obj_class", array("allowed_values"=>null, "sql"=>'obj_class', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeObjectKey("obj_id", array("class_attcode"=>'obj_class', "allowed_values"=>null, "sql"=>'obj_id', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("background_color", array("allowed_values"=>null, "sql"=>'background_color', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeString("text_color", array("allowed_values"=>null, "sql"=>'text_color', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'obj_class',
  1 => 'obj_id',
  2 => 'background_color',
  3 => 'text_color',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'obj_class',
  1 => 'obj_id',
  2 => 'background_color',
  3 => 'text_color',
));
;
	}



	public function IsTarget($sMode)
	{
		return static::IsTargetObject(MetaModel::GetObject($this->Get('obj_class'), $this->Get('obj_id')),$sMode);
	}


	public static function IsTargetObject ($oObject, $sMode)
	{
		$sClass = get_class($oObject);
		$aAllowedClasses = utils::GetConfig()->GetModuleSetting(TimeTrackingView::MODULE_CODE, 'allowed_classes');
		$bIsTarget = false;
		$bIsInAllowed = array_key_exists($sClass, $aAllowedClasses) && array_key_exists($sMode, $aAllowedClasses[$sClass]);
		if ($bIsInAllowed && !empty($aAllowedClasses[$sClass][$sMode]))
		{
			$sOQL = $aAllowedClasses[$sClass][$sMode];
            $oOQL = DBObjectSearch::FromOQL($sOQL);
            $oOQL->AllowAllData(true);
            $oOQL->AddCondition('id', $oObject->GetKey() ,'=');
            $oSet = new DBObjectSet($oOQL, array(), array());
			while($oAllowedObj= $oSet->Fetch())
			{
				if(get_class($oAllowedObj) === get_class($oObject) && $oAllowedObj->GetKey() === $oObject->GetKey())
				{
					$bIsTarget = true;
					break;
				}
			}
		}
		else if ($bIsInAllowed && empty($aAllowedClasses[$sClass][$sMode]))
		{
			$bIsTarget = true;
		}
		else if(!$bIsInAllowed)
		{
			$aParentClasses = MetaModel::EnumParentClasses($sClass, ENUM_PARENT_CLASSES_ALL, false);
			foreach ($aParentClasses as $sParentClass)
			{
				if( array_key_exists($sParentClass, $aAllowedClasses) && array_key_exists($sMode, $aAllowedClasses[$sParentClass]))
				{
					if (!empty($aAllowedClasses[$sParentClass][$sMode]))
					{
						$sOQL = $aAllowedClasses[$sParentClass][$sMode];
                        $oOQL = DBObjectSearch::FromOQL($sOQL);
                        $oOQL->AllowAllData(true);
                        $oOQL->AddCondition('id', $oObject->GetKey() ,'=');
                        $oSet = new DBObjectSet($oOQL, array(), array());
						while($oAllowedObj= $oSet->Fetch())
						{
							if(get_class($oAllowedObj) === get_class($oObject) && $oAllowedObj->GetKey() === $oObject->GetKey())
							{
								$bIsTarget = true;
								break;
							}
						}
					}
					else if (empty($aAllowedClasses[$sParentClass][$sMode]))
					{
						$bIsTarget = true;
					}
					break;
				}
			}
		}
		return $bIsTarget;
	}


	public static function GetTargetObjects($sMode)
	{
		$aAllowedClasses = utils::GetConfig()->GetModuleSetting(TimeTrackingView::MODULE_CODE, 'allowed_classes');
		$aTargetObjects = array();
		foreach($aAllowedClasses as $sClass => $aScopes)
		{
			$bIsInAllowed = array_key_exists($sClass, $aAllowedClasses) && array_key_exists($sMode, $aAllowedClasses[$sClass]);
			if ($bIsInAllowed && !empty($aAllowedClasses[$sClass][$sMode]))
			{
				$sOQL = $aAllowedClasses[$sClass][$sMode];
                $oOQL = DBObjectSearch::FromOQL($sOQL);
                $oOQL->AllowAllData(true);
                $oSet = new DBObjectSet($oOQL, array(), array());
				$aTargetObjects[$sClass] = $oSet->ToArray();
			}
			else if ($bIsInAllowed && empty($aAllowedClasses[$sClass][$sMode]))
			{
				$sOQL = 'SELECT ' . $sClass;
                $oOQL = DBObjectSearch::FromOQL($sOQL);
                $oOQL->AllowAllData(true);
                $oSet = new DBObjectSet($oOQL, array(), array());
				$aTargetObjects[$sClass] = $oSet->ToArray();
			}
		}
		return $aTargetObjects;
	}


	public function IsTargetFromCollection($aCollection)
	{
		$bIsTarget = false;
		foreach($aCollection as $sClass => $oSet)
		{
			$aParentClasses = MetaModel::EnumParentClasses($this->Get('obj_class'), ENUM_PARENT_CLASSES_ALL, false);
			if($this->Get('obj_class') === $sClass)
			{
				foreach($oSet as $oAllowedObj)
				{
					if($oAllowedObj->GetKey() == $this->Get('obj_id'))
					{
						$bIsTarget = true;
						break;
					}
				}
			}
			else if(in_array($sClass, $aParentClasses))
			{
				foreach($oSet as $oAllowedObj)
				{
					if($oAllowedObj->GetKey() === $this->Get('obj_id'))
					{
						$bIsTarget = true;
						break;
					}
				}
			}
		}
		return $bIsTarget;
	}


	public function initializeColors()
	{
		$aColorsParam = utils::GetConfig()->GetModuleSetting(TimeTrackingView::MODULE_CODE, 'colors');
		if (array_key_exists($this->Get('obj_class'), $aColorsParam['classes']))
		{
			$this->Set('background_color', ActivityColors::GetColor($aColorsParam['classes'][$this->Get('obj_class')]['background'], 'background'));
			$this->Set('text_color', ActivityColors::GetColor($aColorsParam['classes'][$this->Get('obj_class')]['text'], 'text'));
		}
		else
		{
			$aParentClasses = class_parents($this->Get('obj_class'));
			foreach ($aParentClasses as $sParentClass)
			{
				if(array_key_exists($sParentClass, $aColorsParam['classes']))
				{
					$this->Set('background_color', ActivityColors::GetColor($aColorsParam['classes'][$sParentClass]['background'],'background'));
					$this->Set('text_color', ActivityColors::GetColor($aColorsParam['classes'][$sParentClass]['text'], 'text') );
					return;
				}
			}
			$this->Set('background_color', ActivityColors::GetColor($aColorsParam['default_calendar']['background'], 'background'));
			$this->Set('text_color', ActivityColors::GetColor($aColorsParam['default_calendar']['text'], 'text'));
		}
	}


	public function getFriendlyName()
	{
		$oObj = MetaModel::GetObject($this->Get('obj_class'), $this->Get('obj_id'));
		if ($oObj != null)
		{
			return $oObj->Get('friendlyname');
		}
		return $this->Get('obj_class') . ' #' . $this->Get('obj_id');
	}


	public static function getOrCreateActivity($iActivity, $sObjClass, $iObjId)
          {
            if ($iActivity <= 0 &&
                $sObjClass &&
                $iObjId &&
                (   Activity::IsTargetObject(MetaModel::GetObject($sObjClass, $iObjId), 'calendar-page') ||
                    Activity::IsTargetObject(MetaModel::GetObject($sObjClass, $iObjId), 'calendar-tab') ||
                    Activity::IsTargetObject(MetaModel::GetObject($sObjClass, $iObjId), 'report-tab') ||
                    Activity::IsTargetObject(MetaModel::GetObject($sObjClass, $iObjId), 'stopwatch')
                ))
            {
        
                $sOQL = 'SELECT Activity WHERE obj_class = :obj_class AND obj_id = :obj_id';
                $aQueryParams = array('obj_class' => $sObjClass, 'obj_id' => $iObjId);
                $oOQL = DBObjectSearch::FromOQL($sOQL);
                $oOQL->AllowAllData(true);
                $oSet = new DBObjectSet($oOQL, array(), $aQueryParams);
                $oActivity = $oSet->Fetch();
                if ($oActivity != null)
                {
                    $iActivity = $oActivity->GetKey();
                }
                else
                {
                    $oActivity = new Activity();
                    $oActivity->Set('obj_class', $sObjClass);
                    $oActivity->Set('obj_id',  $iObjId);
                    $oActivity->initializeColors();
                    $oActivity->DBInsert();
                    $iActivity = $oActivity->GetKey();
                }
            }
            return $iActivity;
        }



	protected function AfterInsert()
	{
		parent::AfterInsert();
		$this->RefreshFriendlyName();
	}


	public function RefreshFriendlyName()
	{
		$sFriendlyName = $this->getFriendlyName();
		$this->Set('label', $sFriendlyName);
		$this->DBUpdate();
	}

}


class FavouriteActivity extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array(			'category' => 'addon,application,bizmodel',
			'key_type' => 'autoincrement',
			'name_attcode' => array('user_id'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(''),
			'db_table' => 'favourite_activity',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, null),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeExternalKey("user_id", array("targetclass"=>'User', "allowed_values"=>null, "sql"=>'user_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("activity_id", array("targetclass"=>'Activity', "allowed_values"=>null, "sql"=>'activity_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("user_id_finalclass_recall", array("allowed_values"=>null, "extkey_attcode"=>'user_id', "target_attcode"=>'finalclass', "always_load_in_tables"=>false)));



;
	}


}


class UserColorActivity extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array(			'category' => 'addon,application,bizmodel',
			'key_type' => 'autoincrement',
			'name_attcode' => array('user_id'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(''),
			'db_table' => 'user_color_activity',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, null),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeExternalKey("user_id", array("targetclass"=>'User', "allowed_values"=>null, "sql"=>'user_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("activity_id", array("targetclass"=>'Activity', "allowed_values"=>null, "sql"=>'activity_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("background_color", array("allowed_values"=>null, "sql"=>'title', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeText("text_color", array("allowed_values"=>null, "sql"=>'text_color', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));



;
	}


}


class TimeSpent extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array(			'category' => 'addon,application,bizmodel',
			'key_type' => 'autoincrement',
			'name_attcode' => array('contact_id_friendlyname', 'start_date'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('contact_id', 'duration', 'org_id', 'start_date', 'user_id'),
			'db_table' => 'timespent',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',
			'style' =>  new ormStyle(null, null, null, null, null, 'itop-time-tracking/img/timespent.png'),
			'archive' => true,);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeExternalKey("user_id", array("targetclass"=>'User', "allowed_values"=>null, "sql"=>'user_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("contact_id", array("targetclass"=>'Contact', "allowed_values"=>null, "sql"=>'contact_id', "is_null_allowed"=>true, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDateTime("start_date", array("allowed_values"=>null, "sql"=>'start_date', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeDateTime("end_date", array("allowed_values"=>null, "sql"=>'end_date', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("activity_id", array("targetclass"=>'Activity', "allowed_values"=>null, "sql"=>'activity_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("activity_label", array("allowed_values"=>null, "extkey_attcode"=>'activity_id', "target_attcode"=>'label', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("org_id", array("targetclass"=>'Organization', "allowed_values"=>null, "sql"=>'org_id', "is_null_allowed"=>true, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("description", array("allowed_values"=>null, "sql"=>'description', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeString("title", array("allowed_values"=>null, "sql"=>'title', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeEnum("origin", array("allowed_values"=>new ValueSetEnum("calendar,stopwatch,manual"), "display_style"=>'list', "sql"=>'origin', "default_value"=>'manual', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeDuration("duration", array("allowed_values"=>null, "sql"=>'duration', "default_value"=>'0', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("user_id_finalclass_recall", array("allowed_values"=>null, "extkey_attcode"=>'user_id', "target_attcode"=>'finalclass', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("contact_id_finalclass_recall", array("allowed_values"=>null, "extkey_attcode"=>'contact_id', "target_attcode"=>'finalclass', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("contact_id_obsolescence_flag", array("allowed_values"=>null, "extkey_attcode"=>'contact_id', "target_attcode"=>'obsolescence_flag', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalField("org_id_obsolescence_flag", array("allowed_values"=>null, "extkey_attcode"=>'org_id', "target_attcode"=>'obsolescence_flag', "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col0' => 
  array (
    'fieldset:TimeSpent:Edition' => 
    array (
      0 => 'start_date',
      1 => 'end_date',
      2 => 'description',
      3 => 'activity_id',
      4 => 'activity_label',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:TimeSpent:Information' => 
    array (
      0 => 'title',
      1 => 'org_id',
      2 => 'user_id',
      3 => 'contact_id',
      4 => 'duration',
      5 => 'origin',
    ),
  ),
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'contact_id',
  1 => 'org_id',
  2 => 'title',
  3 => 'start_date',
  4 => 'user_id',
));
		MetaModel::Init_SetZListItems('default_search', array (
  0 => 'contact_id',
  1 => 'org_id',
  2 => 'start_date',
  3 => 'title',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'activity_label',
  1 => 'org_id',
  2 => 'user_id',
  3 => 'duration',
));
;
	}



	public function GetInitialStateAttributeFlags($sAttCode, &$aReasons = array(), $sTargetState = '')
	{
		$iFlags = parent::GetAttributeFlags($sAttCode, $aReasons, $sTargetState);
        $oUser = UserRights::GetUserObject();
        if((UserRights::HasProfile('Time Tracking Manager', $oUser) || UserRights::IsAdministrator($oUser)) && ($sAttCode === 'contact_id' || $sAttCode === 'user_id'))
        {
          	return $iFlags;
        }
		else if ($sAttCode === 'contact_id' || $sAttCode === 'user_id' || $sAttCode === 'org_id'|| $sAttCode === 'title' || $sAttCode === 'origin' || $sAttCode === 'duration')
		{
			$iFlags |= OPT_ATT_READONLY;
		}
		return $iFlags;
	}


	public function GetAttributeFlags($sAttCode, &$aReasons = array(), $sTargetState = '')
	{
		$iFlags = parent::GetAttributeFlags($sAttCode, $aReasons, $sTargetState);
		$oUser = UserRights::GetUserObject();
        if((UserRights::HasProfile('Time Tracking Manager', $oUser) || UserRights::IsAdministrator($oUser)) && ($sAttCode === 'contact_id' || $sAttCode === 'user_id'))
        {
          	return $iFlags;
        }
		if ($sAttCode === 'contact_id' || $sAttCode === 'user_id' || $sAttCode === 'activity_id' || $sAttCode === 'org_id'|| $sAttCode === 'title' || $sAttCode === 'origin' || $sAttCode === 'duration')
		{
			$iFlags |= OPT_ATT_READONLY;
		}
		return $iFlags;
	}


	protected function OnUpdate()
	{
		parent::OnUpdate();
		$aChanges = $this->ListChanges();
		if (array_key_exists('start_date', $aChanges) || array_key_exists('end_date', $aChanges) )
		{
			$this->UpdateDuration();
		}
	}


	protected function OnInsert()
	{
		parent::OnInsert();
		
		//Set an end time if needed
		if($this->Get('finalclass') === 'TimeSpent' && $this->Get('end_date') === null)
		{
			$sMinimumEventDuration = utils::GetConfig()->GetModuleSetting(TimeTrackingView::MODULE_CODE, 'minimum_event_duration_display', '00:00:00');
            $oStartDate = new DateTime($this->Get('start_date'));

            $oEndDate = clone $oStartDate;
            $aMinimumEventDuration = explode(':', $sMinimumEventDuration);
            $oEndDate->add(new DateInterval('PT'.$aMinimumEventDuration[0].'H'))->add(new DateInterval('PT'.$aMinimumEventDuration[1].'M'))->add(new DateInterval('PT'.$aMinimumEventDuration[2].'S'));
            
            $this->Set('end_date', $oEndDate->format('Y-m-d H:i:s'));
        }
		
		//Set the current user
		$this->SetIfNull('user_id',  UserRights::GetUserId());

		//Set current user's contact
		$this->SetIfNull('contact_id', UserRights::GetContactId());
		
		//Update duration if different rules need to be applied
		$this->UpdateDuration();
		
		//Update activity friendlyname
		$oActivity = MetaModel::GetObject('Activity', $this->Get('activity_id'));
		$oActivity->RefreshFriendlyName();
		
		//Set default title
        $this->SetIfNull('title',  $oActivity->GetFriendlyName());
        
        //Set org id
		$this->SetIfNull('org_id', $this->GetOrganization());
	}


	protected function UpdateDuration()
	{
		if(!empty($this->Get('start_date')) && !empty($this->Get('end_date')))
		{
		    $oStartDate = DateTime::createFromFormat(AttributeDateTime::GetInternalFormat(), $this->Get('start_date'));
		    $oEndDate = DateTime::createFromFormat(AttributeDateTime::GetInternalFormat(), $this->Get('end_date'));
			$this->Set('duration', $oEndDate->getTimestamp() - $oStartDate->getTimestamp());
		}
	}


	public function GetColor()
	{
		$aColorsParam = MetaModel::GetModuleSetting(TimeTrackingView::MODULE_CODE, 'colors');
		$sBGColor = '';
		$sTextColor = '';

		if ($this->Get('origin') === 'calendar')
		{
			if ($this->Get('user_id') == UserRights::GetUserId())
			{
			    $sOQL = 'SELECT UserColorActivity WHERE activity_id = :activity_id AND user_id = :user_id';
				$aQueryParams = array('activity_id' => $this->Get('activity_id'), 'user_id' => UserRights::GetUserId());
				$oSet = new DBObjectSet(DBObjectSearch::FromOQL($sOQL), array(), $aQueryParams);
				$oUserColorActivity = $oSet->Fetch();
				if ($oUserColorActivity != null)
				{
			    	$sBGColor = $oUserColorActivity->Get('background_color');
                    $sTextColor = $oUserColorActivity->Get('text_color');
				}
				else
				{
                  $sOQL = 'SELECT Activity WHERE id = :activity_id';
                  $aQueryParams = array('activity_id' => $this->Get('activity_id'));
                  $oSet = new DBObjectSet(DBObjectSearch::FromOQL($sOQL), array(), $aQueryParams);
                  $oActivity = $oSet->Fetch();
                  if ($oActivity != null)
                  {
                      $sBGColor = $oActivity->Get('background_color');
                      $sTextColor = $oActivity->Get('text_color');
                  }
				}	
			}
			else
			{
				$sBGColor = ActivityColors::GetColor($aColorsParam['default_calendar']['background']);
				$sTextColor = ActivityColors::GetColor($aColorsParam['default_calendar']['text']);
			}
		}
		else if ($this->Get('origin') === 'stopwatch')
		{
			$sBGColor = ActivityColors::GetColor($aColorsParam['default_stopwatch']['background']);
			$sTextColor = ActivityColors::GetColor($aColorsParam['default_stopwatch']['text']);
		}

		return array($sBGColor, $sTextColor);
	}


	public function GetOrganization()
	{
		$iOrgId = null;
		$iActivityId = $this->Get('activity_id');
		if(!empty($iActivityId))
		{
		  $oActivity = MetaModel::GetObject('Activity', $iActivityId);
		  $oActivityObject = MetaModel::GetObject($oActivity->Get('obj_class'), $oActivity->Get('obj_id'));
		  if(MetaModel::IsValidAttCode($oActivity->Get('obj_class'), 'org_id'))
		  {
		     $iOrgId = $oActivityObject->Get('org_id');
		  }
		}
		return $iOrgId;
	}


public function PrefillCreationForm(&$aContextParam)
		{	
		    $oStartDate = new DateTime();
		    if(isset($aContextParam['start-timestamp'])){
                $oStartDate->setTimestamp($aContextParam['start-timestamp']);
            }
            $this->Set('start_date',  $oStartDate->format('Y-m-d H:i:s'));
            if(!isset($aContextParam['time-tracking-step']) || (isset($aContextParam['time-tracking-step']) && $aContextParam['time-tracking-step'] !== 'start-stopwatch'))
            {
                $oEndDate = new DateTime();
                if(isset($aContextParam['end-timestamp'])){
                  $oEndDate->setTimestamp($aContextParam['end-timestamp']);
                }
                $this->Set('end_date',  $oEndDate->format('Y-m-d H:i:s'));
            }
            $this->Set('description',  '');
            $this->Set('origin', 'calendar');
            $this->Set('user_id',  UserRights::GetUserId());
            $this->Set('contact_id', UserRights::GetContactId());
		}

}


class TimeSpentBackground extends TimeSpent
{
	public static function Init()
	{
		$aParams = array(			'category' => 'addon,application,bizmodel',
			'key_type' => 'autoincrement',
			'name_attcode' => array('contact_id_friendlyname', 'start_date'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(''),
			'db_table' => 'timespent_background',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, null),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeEnum("status", array("allowed_values"=>new ValueSetEnum("ongoing,stopped,force-stopped"), "display_style"=>'list', "sql"=>'status', "default_value"=>'ongoing', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col0' => 
  array (
    'fieldset:TimeSpent:Edition' => 
    array (
      0 => 'start_date',
      1 => 'end_date',
      2 => 'description',
      3 => 'activity_id',
      4 => 'activity_label',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:TimeSpent:Information' => 
    array (
      0 => 'title',
      1 => 'org_id',
      2 => 'user_id',
      3 => 'contact_id',
      4 => 'duration',
      5 => 'origin',
    ),
  ),
));
;
	}


}


class TriggerOnForceStopTimeSpentBackground extends TriggerOnObject
{
	public static function Init()
	{
		$aParams = array(			'category' => 'core/cmdb,application',
			'key_type' => 'autoincrement',
			'name_attcode' => array('description'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(),
			'db_table' => 'priv_trigger_onforcestoptimespentbackground',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, null),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();



		MetaModel::Init_SetZListItems('details', array (
  0 => 'description',
  1 => 'filter',
  2 => 'action_list',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'finalclass',
  1 => 'target_class',
  2 => 'description',
));
;
	}



	public function OnInsert()
    {
        parent::OnInsert();
        $this->Set('target_class', 'TimeSpentBackground');
    }

}
//
// Menus
//
class MenuCreation_itop_time_tracking extends ModuleHandlerAPI
{
	public static function OnMenuCreation()
	{
		global $__comp_menus__; // ensure that the global variable is indeed global !
		$__comp_menus__['TimeTracking'] = new MenuGroup('TimeTracking', 65, 'fas fa-user-clock' , 'TimeSpent', UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['TimeTrackingPage'] = new WebPageMenuNode('TimeTrackingPage', utils::GetAbsoluteUrlModulePage('itop-time-tracking', "calendar-tracking.php"), $__comp_menus__['TimeTracking']->GetIndex(), 1 , 'TimeSpent', UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['MyTimeTrackingReport'] = new WebPageMenuNode('MyTimeTrackingReport', utils::GetAbsoluteUrlAppRoot()."pages/exec.php?exec_module=itop-time-tracking&exec_page=report.php&mode=self", $__comp_menus__['TimeTracking']->GetIndex(), 10 , 'TimeSpent', UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['TimeTrackingReport'] = new WebPageMenuNode('TimeTrackingReport', utils::GetAbsoluteUrlAppRoot()."pages/exec.php?exec_module=itop-time-tracking&exec_page=report.php", $__comp_menus__['TimeTracking']->GetIndex(), 20 , 'TimeSpent', UR_ACTION_BULK_DELETE, UR_ALLOWED_YES, null);
	}
} // class MenuCreation_itop_time_tracking
