{{- if .Values.mariadb.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-database
  labels:
    {{- include "itop-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: {{ include "itop-chart.mariadb.fullname" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "itop-chart.selectorLabels" . | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mariadb-operator
      ports:
        - port: {{ .Values.mariadb.instance.port }}
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
