{{- if and .Values.mariadb.enabled (not .Values.mariadb.auth.existingSecret) }}
{{- $secretName := include "itop-chart.mariadb.secretName" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $existingData := dict }}
{{- if $existingSecret }}
{{- $existingData = $existingSecret.data }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "itop-chart.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ get $existingData "root-password" | default (randAlphaNum 32 | b64enc) }}
  password: {{ get $existingData "password" | default (randAlphaNum 32 | b64enc) }}
{{- end }}
