name: Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-push:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Build/Push
      uses: coopTilleuls/action-docker-build-push@v10
      with:
        IMAGE_NAME: itop-apache
        BUILD_CONTEXT: 3.0-custom
        REGISTRY_JSON_KEY: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPOSITORY: ghcr.io/cooptilleuls
        SECURITY_SCAN: false

